### ISSUE TITLE
Large Data Resource not displaying properly

### ISSUE THREAD

**Issue by fbrooks1056** [NuCivic/dkan#1101]
## Description

When working with large files, DKAN is not able to visualize a preview  
## Steps to Reproduce
1. Create a data resource with an uploaded file greater than 60mb 
2. When you try to preview the resource after creation you get 
   ![image](https://cloud.githubusercontent.com/assets/10466565/14927477/ccaffaa8-0e17-11e6-8fae-5f3403b2044b.png)
## Ticket Reference

NCS-296

**Comment by msolv** [comment]
@fbrooks1056 That is not a bug. If a file is too big it should be imported on a datastore in order to be previewed. 

Files that are not imported on a datastore will be downloaded by dkan and when the file is too big the download is cancelled due to a timeout. That's the reason of the 'File was too large...' message.

**Comment by msolv** [comment]
@fbrooks1056 The preview timeout can be increased if needed here going to /admin/dkan/recline
