### ISSUE TITLE
Upload form error: Undefined index: #file_resup_upload_validators

### ISSUE THREAD

**Issue by SmallhillCZ** [NuCivic/dkan#1124]
Getting following error when displaying the upload form:

Notice: Undefined index: #file_resup_upload_validators in function dkan_dataset_form_alter() (line: 217 in file E:\Apache24\htdocs\profiles\dkan\modules\dkan\dkan_dataset\dkan_dataset.forms.inc).

**Comment by dafeder** [comment]
@SmallhillCZ could you give us some more information about your codebase? What version of DKAN? Have you upgraded from a previous version or just got this after installing from scratch?

**Comment by bluefedora** [comment]
same problem....

Notice: Undefined index: #file_resup_upload_validators in dkan_dataset_form_alter() (line 217 of /var/www/html/dkan/profiles/dkan/modules/dkan/dkan_dataset/dkan_dataset.forms.inc).

version = 7.x-1.12.6

problem was there in the previous version 12.5, not sure if it was there in previous versions

**Comment by dafeder** [comment]
@bluefedora this appears every time you view the upload form? Are you able to upload anyway?

**Comment by bluefedora** [comment]
Yes, and yes. 

It appears twice when attempting to upload simply by going to the upload form; and every time when when simply going to the "edit" page; and every time I try to "Remove" or "Upload" from the "edit" page although both remove and upload succeed.

Unrelated (thought I'd mention it since the error message includes something that may be related to file validation)? I'm having trouble viewing geojson as geojson doesn't seem to be recognized as a file that is "supported for preview".

Many thanks,

**Comment by janette** [comment]
@SmallhillCZ could you try upgrading to the latest release? https://github.com/NuCivic/dkan/releases Many improvements have been made and if you still have upload errors please open a new ticket.
