### ISSUE TITLE
DKAN previous full made versions

### ISSUE THREAD

**Issue by bndri** [NuCivic/dkan#1238]
Sorry for disturbing you. I searched on the net and I have not found a page of previous full made versions of DKAN. I mean dkan-7.x-1.10, dkan-7.x-1.11, dkan-7.x-1.12, dkan-7.x-1.12.1, dkan-7.x-1.12.2.
Can anyone give me the link?
Thank you

**Comment by dafeder** [comment]
Hello - we're rethinking how we distribute fully made versions of DKAN given that for now DKAN is not packaged on Drupal.org due to licensing issues with certain libraries. For now I would recommend using the [DKAN DROPS](https://github.com/NuCivic/dkan-drops-7) repo and finding the commit that corresponds to the release you want:

## 1.
![2016-07-06_08-26-21](https://cloud.githubusercontent.com/assets/309671/16617748/77cb6524-4353-11e6-9747-3a773915a152.png)

## 2. 
![2016-07-06_08-26-59](https://cloud.githubusercontent.com/assets/309671/16617751/7ca0b194-4353-11e6-8823-bf09e92a9f37.png)

## 3. 
![2016-07-06_08-27-17](https://cloud.githubusercontent.com/assets/309671/16617758/8078363e-4353-11e6-80a1-2a15706c283b.png)

**Comment by bndri** [comment]
Thank you Dafeder
