### ISSUE TITLE
Private datasets for group members

### ISSUE THREAD

**Issue by lecegit** [NuCivic/dkan#498]
When editting user permissions, I didn't find the way to allow users to view datasets only from groups they belong. 
If I uncheck the "View published content" permission for authenticated user, then no datasets are shown, even if "Group: Create new content" and "Group: Edit own content" are checked. If "View published content" is checked, no matter wich group, authenticated users can see all datasets including those created by groups they're not members.
How can I setup user permissions for view published content only in groups users belong?

**Comment by janette** [comment]
Documentation on permissions: http://dkan.readthedocs.io/en/latest/components/permissions.html

@lecegit DKAN is an open data portal so it is configured so that all datasets are public. If you wanted to restrict access you would need to add config changes that would make it difficult to upgrade your site when future releases come out. However...

1. Navigate to `admin/config/group/fields`
2. Under 'Bundles' select 'Group'
3. Under 'Fields' select 'Group content visibility'
4. Click 'Add field'
5. Navigate to a group node and click 'Edit', you will see a field where you can select the visibility settings for group content.

**Comment by kittipon-mot** [comment]
Private datasets for group members in DKAN2 ?

**Comment by kitsunemax** [comment]
Can anyone confirm private datasets for group members in DKAN2 ?? [https://github.com/GetDKAN/dkan/issues/498#issuecomment-697273449](https://github.com/GetDKAN/dkan/issues/498#issuecomment-697273449)

ALSO ... is there a way to enable hierarchy in groups - so parent child relations, that then respect the dataset permissions as well ???
