### ISSUE TITLE
Get dkan_datastore feed importers off features.

### ISSUE THREAD

**Issue by drkloc** [NuCivic/dkan#517]
See NuCivic/dkan_datastore#43 for context

**Comment by tenken** [comment]
Hi. I was looking at DKAN over the last few days because we're moving a legacy site into drupal and it contains alot of historical data and essentially datasets. I could really use dkan_datastore in this project. I found these directions to tie it to my own drupal project:
https://github.com/NuCivic/dkan_datastore#using-without-dkan

But, after implementing those hook functions, the Feeds imported bundled via Features is still hardcoded to a "dataset" content type and a "resource" field.

So for my needs I overrode these values for my needs and the module works fine outside of DKAN. I recommend updating directions in the README to detail how datastore should be implemented outside of DKAN if that will still (hopefully) be supported after Feeds is un-featurized.

Thanks for great tools and workflows you guys support in your distribution.

**Comment by drkloc** [comment]
@tenken, we move it back temporarily because we were having an issue with overridden features on the dkan distro. The feed importer is clearly not designed to be a feature anymore with those function calls.

I've began working on this here but couldn't make it work properly yet -> https://github.com/NuCivic/dkan_datastore/pull/44

Please take a look, you are more than welcome to build on that or even propose an alternative if you have ideas already.

**Comment by acouch** [comment]
@tenken You can use a alter hook to update the node type https://github.com/NuCivic/dkan_datastore/blob/7.x-1.x/dkan_datastore.module#L491

**Comment by drkloc** [comment]
This could be achieved through hooks. Closing.
