### ISSUE TITLE
QA: Site Lost Custom Hero Image

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#589]
As an admin on http://stefanie.dkandemo.nuamsdev.com/, I uploaded a custom hero image last night. This morning, it was missing and was replaced with the DKAN default. No other options or uploads were missing or modified.

**Comment by dafeder** [comment]
Haven't seen this come up since; going to assume it was a glitch.

**Comment by sheldonrampton** [comment]
I've been seeing this happen on the Marine Scotland website (currently running DKAN 7.x-1.9), so I'm reopening this issue.

**Comment by sheldonrampton** [comment]
I've seen this happen now at least half a dozen times on the test instance of the Marine Scotland website. Every time I re-upload the custom hero image, it reverts to the default hero image within 24 hours. I haven't been able to identify what is causing this to happen. I'm not able to recreate the error manually. I've tried clearing caches, running cron, and resaving colorizer settings, none of which seem to produce the error. I also have not seen anything in the Drupal logs that appears linked to the error. The only way I've found to reproduce the error is just to wait 24 hours and then revisit the website. In order to prevent the issue from visually impacting the Marine Scotland website, I've hacked the site code so that the default image at path /profiles/dkan/themes/contrib/nuboot_radix/assets/images/hero.png (instead of hero.jpg) contains Marine Scotland's hero image instead of the normal DKAN hero image. This masks the symptoms, but the underlying bug still exists. The attached screenshot shows that after I upload the custom hero image (filename Altbg.png), it appears on the front page. After 24 hours, however, it will revert to the the hero.png file. Since the two files are identical, the problem is only detectable by inspecting the page HTML.

![image](https://cloud.githubusercontent.com/assets/2838758/11402690/cd0971fc-935e-11e5-9ef2-2028c4e80c1c.png)

**Comment by janette** [comment]
This problem occurs when a site is not using a subtheme. The custom panel template was poorly implemented (by me) and processes the hero image file from the template rather than with a preprocess function. The template will ignore the new hero image and look for the nuboot_radix/assets/images/hero.jpg
https://github.com/NuCivic/nuboot_radix/blob/7.x-1.x/panels/layouts/full_width/panels-full-width.tpl.php

The NEW nuboot_radix https://github.com/NuCivic/nuboot_radix/pull/62 has fixed this by moving the template variables to preprocess functions where they belong.
https://github.com/NuCivic/nuboot_radix/blob/radix-structure-update/includes/panel.inc

**Comment by janette** [comment]
Update: the uploaded hero file still disappears when using the revised nuboot_radix (LKY) more investigation needed.

**Comment by sheldonrampton** [comment]
fix is here https://github.com/NuCivic/nuboot_radix/pull/65
