### ISSUE TITLE
"Tag" list only scrolls 10 entries

### ISSUE THREAD

**Issue by amcnally** [NuCivic/dkan#825]
Steps to Reproduce:
Click "Add Dataset"
In the "Tags" field, enter a common value
You can only scroll down 10 entries, though there may be more.

Request: Add tag scroll and search capabilities to this field.

For more information:
https://github.com/NuCivic/External-HHS/issues/290
https://github.com/NuCivic/External-HHS/issues/12

**Comment by janette** [comment]
https://www.drupal.org/node/1799462

This is a feature! The field is using the **autocomplete_deluxe** widget which has a hard coded limit on how many terms to display because displaying too many terms would slow the widget down. Since users are able to add as many tags as they wish the list could get enormous. As the user types any matching terms will pop into the 'list'.
