### ISSUE TITLE
Datastore Import Error

### ISSUE THREAD

**Issue by jasoneverettmiller** [NuCivic/dkan#891]
Tried to import a 3MB CSV file into the datastore and received the following error message:

> SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'certificateofoccupancydate' at row 1" 

After shortening the column header to "OCCUPANCYCERTDATE" (17 characters vice 26) was able to import without a problem.

The site in question is running on the 7.x-1.x branch.

**Comment by dafeder** [comment]
Seems to be an issue with column type. Flagging as a bug but may not be worth fixing as the datastore is due for a larger revamp.

**Comment by kynetiv** [comment]
I'm wondering if I'm running into this as well.. I have mostly longwinded column header names (around 28 characters) and my import gets hung on 'initializing'.

Any ideas for a workaround to allow longer header names, or where I might look to tune this (outside of renaming the columns)?

**Comment by kynetiv** [comment]
Just an update, it looks like for me it wasn't a column name length issue, as my import was able to parse column names with 32 characters.  It looks like it was too many rows. I truncated my 67mb csv file down to 100 rows making it less than 1 mb and it was able to handle it. I suppose I need to open a ticket elsewhere.

**Comment by dafeder** [comment]
@kynetiv we have run into this same issue. When we've seen it, it's because the datastore creates a schema for the table based on guessing the column types based on the data in the first 1000 rows, but then encounters a row that is not compatable with the column type. For instance, you might have a dataset that starts with a few hundred blank values in one column, but then has a text value later on.

If you can confirm this as the likely cause by looking at your CSV, you could use your mysql client to manually alter the problem column type and then try re-importing all items.

**Comment by kynetiv** [comment]
Well, not to hijack this thread anymore, but I was able to import the full spreadsheet. It looks like it was more or less a memory_limit issue :( . I up'd it to 4096M and it did complete, however, it didn't import all my columns. I have 1729 columns and it only imported 653 columns. So now I'm looking at another issue i guess.
